"""add_module_to_audit_logs

Revision ID: 0e12ca119a30
Revises: f3f810095ccf
Create Date: 2026-08-06 17:06:51.782260

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0e12ca119a30"
down_revision: Union[str, Sequence[str], None] = "f3f810095ccf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "module",
                sa.String(length=50),
                nullable=False,
                server_default="system",
            )
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.drop_column("module")
    # ### end Alembic commands ###
