"""add project_departments join table

Revision ID: cd0bc963b952
Revises: b2c3d4e5f6a7
Create Date: 2026-08-07 19:09:17.207756

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cd0bc963b952"
down_revision: Union[str, Sequence[str], None] = "b2c3d4e5f6a7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("projects_department_id_fkey"), type_="foreignkey"
        )
        batch_op.drop_column("department_id")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("department_id", sa.UUID(), autoincrement=False, nullable=True)
        )
        batch_op.create_foreign_key(
            batch_op.f("projects_department_id_fkey"),
            "departments",
            ["department_id"],
            ["id"],
            ondelete="SET NULL",
        )

    # ### end Alembic commands ###
